### PR TITLE
add refs/heads/ prefix to push commands

### PR DESCRIPTION
**Pull request by askvinni**
### Type of Change

- [X] Bugfix
- [ ] Enhancement / new feature
- [ ] Refactoring
- [ ] Documentation

### Description

A team member accidentally pushed a tag named `dev` into one of the repos, causing this workflow to fail as it couldn't disambiguate between the tag and branch. This fix should do the trick.

See https://github.com/Staffbase/data-platform/actions/runs/12118914306/job/33785057104 for `error: src refspec dev matches more than one`

### Checklist

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Review the [Contributing Guideline](https://github.com/Staffbase/yamllint-action/blob/main/CONTRIBUTING.md) and sign CLA
- [ ] Reference relevant issue(s) and close them after merging

### CODE REVIEW

**Comment by askvinni** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Comment by askvinni** [comment]
recheck

**Review by flaxel — COMMENTED** [review]
If you finished all your action please run the following command and push your changes:
```bash
pnpm run all
```

**Review by flaxel — APPROVED** [review]

**Comment by askvinni** [comment]
No immediate need to release this one as we already solved the problem by deleting the `dev` tag in the repo, but I wanted to future proof it in case it happens again.

**Pull request merged**
